# Generated by Django 2.2 on 2019-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='select',
            field=models.CharField(choices=[('Model Feed', 'Model Feed'), ('News Feed', 'News Feed'), ('Other Feed', 'Other Feed')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
